### ISSUE TITLE
Pricing: Limits & upgrade plan

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#716]
![pricing-limit](https://user-images.githubusercontent.com/34077077/41867730-883bad80-7879-11e8-801d-96ee2598742b.png)

Here the screen for the updated plan due to limit reach. 
We would need to monitor:
a) # of skills;
b) # of logs.

The message would be:
a) You have reached the maximum number of skills allowed by your subscription. 
Please upgrade your plan to add more skills.

b) You have reached the maximum number of logs allowed by your subscription. 
Please upgrade your plan to monitor more logs.

**Comment by robertonotte** [comment]
New version addressing Ken comments:
* the Go button is not entirely center (we can leave that to pier to fix)
* Do we have a close button or an "x" appears in the corner when we hover the popup or maybe **### just clicking outside close the pop up** (The correct response should be the same as the other behaviors on the other popups) 
* The Llama is saying oops, I like it, but I think is the same picture as the one on payment so we probably want to show the same type of llama but with a different expression 
* Double check with Pier if the "Go" button is according of the expected design that he is working on 
* If possible give us a complete version of the popup without adding ....... to see how the user will see it

![pricing-limitvs2](https://user-images.githubusercontent.com/34077077/41868545-f911de24-787b-11e8-9df7-d96d45e5a6bb.png)

**Comment by GitBoHub** [comment]
- Reduce the size of the Oops bubble. It should not be the largest font on the popup. I recommend reducing the size so it fits inside the colored block. It will give us more room for text on the right side and it will keep the design clean between the two sides.

- We can use this sample text below to continue to collect feedback.
Option for skills: Please upgrade your plan to add more voice apps to your Bespoken account.

Option for logs: Your account is over the number of logs included in your subscription. Please select a new plan to continue testing and monitoring your voice apps.

- Is this our first popup message? I like the idea of using a small x in the corner to give users the option to close.

- Instead of Go on the button, we need to say something more descriptive so people know what they are clicking on. I recommend changing button text to: View Pricing

**Comment by jperata** [comment]
@GitBoHub , @MKen-li 
This is not the first popup
<img width="1167" alt="screen shot 2018-06-25 at 4 03 23 pm" src="https://user-images.githubusercontent.com/8781604/41875741-72778f10-7891-11e8-84e7-2a0ef9c9013a.png">
Our current popup's doesn't have "X" to close, just click outside the popup

**Comment by GitBoHub** [comment]
@MKen-li @jperata That leaves us with two options. Should we add a cancel option to the pricing popup or add an x to existing popups? How many more popups do we have?

**Comment by robertonotte** [comment]
Neither way in my opinion. This is an upselling pop-up, that is an operational pop-up.
I have intentionally omitted the "X" as it will reduce conversions.
