### ISSUE TITLE
Payment Feature Issues.

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#737]
**Preconditions**
log in to the system with a free account

**Bugs**

1. The Label your plan shows "Alpaca" instead of the current plan
2. If I'm not in the source page and I try to subscribe to a plan the back options disappear in the Payment Page.
3. If I use multi tab or multi browsers to enable more than 1 skill at the time the validation doesn't happen. 
4. We should have Free plan explain somewhere in the page.
5. The style of the subscribe button doesn't match the standards of the page.
6. When we are on the Payment Page we have the skill drop down that is useless
7. We need to show the plan date (When did I subscribe and when does the month end)
8. When we use a card that is not in $ there is an extra feed for change currency that we must show. 
9. Increase the spacing between "Current Plan" and the other labels in the Payment plan Page.
10. I should have an option to go back to the payment plans from the payment form. Currently the only way is to click Upgrade Plan which is not that intuitive.
11. The "oops" pop up is way to big, we have so many empty space we could also reduce the font of the text, is bigger that our buttons
12. The Payment Plan page looks like is part of a different system ( no options on the back and just the llama to return to the source page) 
13. The alpaca that appears in the Payment Page should be the same as the llama of the payment plan selected.
14. We need a limit or characters for the postal code. 
15. Add logos of the accepted cards to the payment page.
16. The user can't use another card once is subscribe.

Missing Functionality:

1. Unsubscribe: Just adding this to the ticket for tracking purposes.
2. What do we do when the payment card runs out of funds or is blocked?
3. Should a user be able to change between plan without any restrictions? how do we calculate the cost of the month with a constant change. 
4. Add a message when downgrading a plan
5. What do we do when the logs pass the limit plan?

@jperata @dmarvp @jkelvie @robertonotte 
 

**Screenshots**
None.

**Environment:**
 - OS: Win
 - Browser Chrome
 - Version Dev-79

**Comment by jperata** [comment]
For the actual scope:
We **won't** consider the points:
3. If I use multi tab or multi browsers to enable more than 1 skill at the time the validation doesn't happen.
4. We should have Free plan explain somewhere in the page.
7.  We need to show the plan date (When did I subscribe and when does the month end)
8. When we use a card that is not in $ there is an extra feed for change currency that we must show. 
12. The Payment Plan page looks like is part of a different system ( no options on the back and just the llama to return to the source page)
13. The alpaca that appears in the Payment Page should be the same as the llama of the payment plan selected.
15. Add logos of the accepted cards to the payment page.

Missing Functionality:
1.    Unsubscribe: Just adding this to the ticket for tracking purposes.
- Agree this will be addressed in future iterations

2.     What do we do when the payment card runs out of funds or is blocked?
- For this we need an extra functionality in order to support external calls from stripe.
3.     Should a user be able to change between plan without any restrictions? how do we calculate the cost of the month with a constant change.
- Yes, we give them the difference for free until next billing period.
4.     Add a message when downgrading a plan
- Will be done
5.     What do we do when the logs pass the limit plan?
- sales@bespoken.io will receive an email with the user email, his plan and the logs count when the user log in if the user has more logs than the limit. Sales will encourage the user to do the upgrade.

**Comment by dmarvp** [comment]
@MKen-li can we close this one?
