### ISSUE TITLE
Research: Where to store plans benefits.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#793]
The plan benefits (number of logs, number of monitored skills, etc) seem to be currently stored in env variables and as default values. Decide on the best place to store this data: as stripe metadata? in a collection inside firebase? in env variables or a config file?

The result should be a place where it's easy to change that data without much intervention or changes to the code. Take in mind that there are free and custom plans that are not stored in stripe and this should work for those too.

Based on the results of this research we'll create a ticket to update the code if necessary so that nothing is hardcoded anymore.

**Comment by jperata** [comment]
As part of this review the current logs limitations where we send the email to sales

**Comment by jperata** [comment]
At the moment the current logs limitation is set by the circle environment variables in case the value is set to production:
            process.env.STANDARD_LLN 
            process.env.FREE_LLN 
            process.env.PRO_LLN 

Bussiness is not set up, which is a bug i'm going to attach and reference.

The plan details that can be changed are all the ones not including price (if you need a new price you would need a plan), the name can be changed, and that is what is being used to compare the plan registered in stripe for the user with the benefits that are currently in environment variables.
 
Since we would need to
a) Modify manually the data for business users (some may have different number of virtual devices, others may have unlimited everything)
b) Account for the free plan which also can not be registered regularly on stripe.


The best approach would be to:

a) Save the plans as a different structure in firebase (apart from the existing ones (users, sources) for free, pro and standard plans)
b) For the business plan user using the same structure add a new filed (benefits or similar name) which contains the same attributes of the plans but it's matched to this specific user.
c) When obtaining the user, if the user don't have a benefits attribute added to it, make the endpoint return it with the benefits field filled with that data, data for this benefit field would be dynamic since when the benefits for the free plan is updated for example we don't want to update everything again.

**Comment by dmarvp** [comment]
Code changes to be handled in #823
