### ISSUE TITLE
Research: What happens when a monthly payment fails?

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#794]
In order to define a flow for when a monthly payment fails, we need to know what happens when it does right now. Do we get an email or alert from stripe? How does our system react? 

Based on this findings we can define what to do next, either creating a code flow to manage this or a manual one.

**Comment by jperata** [comment]
**Current State** 
At the moment there are two possible moments where the payment fails
1.- It fails when the user is setting up his first payment by selecting a plan an adding a credit card.  
In this scenario, the endpoint will return to us what went wrong for the  payment,  we return that error to the user (in the most common cases we have our own errors and for the other ones we grab the error that stripe send to us). Since the process failed during the process the process is incomplete and the user can try again with another card by restarting the flow.

2.- It fails during a recurring payment 
At the moment in this scenario, stripe register the error, we can see it inside the platform on https://dashboard.stripe.com/payments but we don't get further communication on that regard. The user that wasn't able to pay get three more attempts at charging the card during the next 3 weeks. At the moment he don't get any communication either. If after that time he hasn't paid yet the plan is cancelled an no further attempt to charge the user is made.

**Resources we have** 
1.- Webhooks
Stripe manages [webhooks](https://stripe.com/docs/billing/webhooks) that sent an event during the different states a payment get through. If we set them, we can customize what to do during those steps, it's not necessary that we implement a single flow for each of the different events, as part of the flow can be handled directly from stripe. The main benefit we get from this is the ability to change the state of our customers directly, to revert them back to a free plan or sent sales an email so that they are aware of it.

2.- Stripe Settings
The plans itself have a few [settings](https://dashboard.stripe.com/account/recurring) that we can tweak,
<img width="940" alt="screen shot 2018-09-07 at 11 21 48 am" src="https://user-images.githubusercontent.com/8781604/45230989-43f58a00-b290-11e8-87b7-78ec0ea8ca5d.png">
 these include enabling sending an email to the user on each failure attempt to charge him, also to sent an alert if his card is one month from the expiration time. This ones still need some more setup in order to be enabled (at the moment it always link to https://bespoken.io, instead of dashboard, and indicates to communicate with Daisy instead of a sales or support account).

**Sample flows**
Without further development only possible flow for failed payments is to find about them manually, and if the subscription have been marked at cancelled on stripe, edit the user directly on the database in order to revert them to a free plan, and then further communication with them.

If we enable and complete a webhook development, our options range from just notify by email on a user subscription being cancelled (eliminating the need to check constantly on stripe), and then we can expand to automatically changing his current plan, or sent warnings to sales once they have a couple of failed attempts.
Changing to a webhook approach may also affect slightly the first payment flow, since if the webhook doesn't respond stripe stop all transactions until it works correctly. (Once you set webhooks is implied that your flow responds to them so if they are not working it would be problematic if stripe keep working as normal).

**Comment by dmarvp** [comment]
Thanks @jperata , I'm closing this one for now, and will create stories for the next quarter based on your recommendations.
