### ISSUE TITLE
My account: Change Password

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#865]
### Summary

As a user of Dashboard
I want to be able to change my password

### Acceptance Criteria (TBD)

1. GIVEN: 
I'm a user of dashboard
I have entered using email and password (not login with Amazon or login with Github)
WHEN: 
I go into "My account" page
THEN:
    - I see under User Details a "Change password" link next to the user's email
    - The "Delete my account" link moves below "Change Password"

2. GIVEN: I'm in "My account" page.
WHEN: I click on "Change Password"
THEN: A modal window appears:
    - Title: Change password.
    - Current password input (should show asterisks instead of letters)
    - New password input (should show asterisks instead of letters)
    - Repeat password input (should show asterisks instead of letters)
    - Cancel and Save buttons (Save button is disabled)

3. GIVEN: The modal is open.
WHEN: I enter the current and new passwords into their inputs.
THEN: The Save button is enabled.

4. GIVEN: The modal is open, I have entered the inputs correctly, the save button is enabled.
WHEN: I click on Save
THEN: 
    - The password is updated in the database
    - The modal window is closed
    - A message appears (we can use a Snackbar for now): "Success! your password has been updated."

5. GIVEN: The modal is open.
WHEN: I click on Cancel
THEN: 
    - The password is not updated.
    - The modal window is closed

6. GIVEN: The modal is open, the save button is enabled.
WHEN: I enter a wrong "current" password and click save.
THEN: 
    - The password is not updated.
    - The modal window is not closed
    - A message in red appears above the buttons: Your current password is wrong. Please, try again.

6. GIVEN: The modal is open, the save button is enabled.
WHEN: I enter a new password that does not match the "repeat password" input.
THEN: 
    - The password is not updated.
    - The modal window is not closed
    - A message in red appears above the buttons: Passwords do not match. Please, try again.

### Additional Resources
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/6411740/45577653-a0cde300-b842-11e8-8633-366aba02ba47.png">

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/6411740/45785993-0ac7fd00-bc34-11e8-95de-e5e714ccb142.png">

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/6411740/45786242-2da6e100-bc35-11e8-92a9-bccedf5ea9db.png">

### NOTES
This will only work for users that access with email and password, not for users login in with Amazon or Github.

**Comment by jperata** [comment]
Posible edge case: 
- Since users can login with github and amazon directly, in that case they won't be able to include the old password, so the functionality should be excluded for persons that have exclusively a github or amazon user. 
- Users that have both a user/password login and an amazon one (since we merge users with same email at least for amazon), can enter in the reset password flow correctly.

**Comment by dmarvp** [comment]
Good catch @jperata , I'll consider those when writing the AC's.

**Comment by dmarvp** [comment]
@jperata can you confirm that we merge amazon and email users? and explain how does that work? that would be the only case remaining.

**Comment by jperata** [comment]
The way in which our authentication works is that we have 3 different ways to ask firebase if our user exists, a custom token (that's what we use for Amazon), a valid provider (Github), or an email and password.
Once firebase tell us that the user did a valid login what we do is go and grab the email of the user and get the user id and generate an authentication token that is returned for the user session to be mantained and valid. Since we only depend on the user email for that at that point regardless of the user way of login the user will be the same.
If you see the users on the firebase database you will see that there are users with no provider, with github provider or with an email sign.
Since we don't have a way of get the existing password (only firebase can match that data), github and amazon users that don't have a regular login won't have an existing password to set up, we could make them login again at that point. A route we could take is grab the way in which the user login at the time, so that you can only update your password if you have login via user and password, and trigger a  login button to amazon or github if you log in on that providers.

**Comment by MKen-li** [comment]
Blocked until the next bugs are fixed:
https://github.com/bespoken/dashboard/issues/889
https://github.com/bespoken/dashboard/issues/890
https://github.com/bespoken/dashboard/issues/891
https://github.com/bespoken/dashboard/issues/892
https://github.com/bespoken/dashboard/issues/893
https://github.com/bespoken/dashboard/issues/894
https://github.com/bespoken/dashboard/issues/895

**Comment by MKen-li** [comment]
Marked as verified
Build dev-151
