### ISSUE TITLE
Delete my account

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#912]
### Summary

As a user of the dashboard 
I want be able to delete my account
so that all my info is removed from the bespoken dashboard

### Acceptance Criteria

1. GIVEN: I'm on my account page.
WHEN: I click on the "Delete my account" link
THEN: I see a modal window
- Title: Warning
- Text: 
```
"This will delete your Bespoken Dashboard account, as well as your registered voice apps and virtual devices. This process can't be undone. 

Are you sure that you want to proceed? If so, please type in "yes delete my account" to proceed.
```
- an empty textbox
- Buttons: Cancel, Ok (will be disabled until the user enters "yes delete my account" in the textbox)

2. GIVEN: I'm looking at the warning modal.
WHEN: I click Ok.
THEN:
- My user account is deleted
- My sources are deleted
- My virtual devices are deleted
- The user is removed from Intercom 
- Any subscription to a paid plan is removed.
- I'm logged out of the dashboard.

### Additional Resources
https://firebase.google.com/docs/auth/web/manage-users
https://developers.intercom.com/intercom-api-reference/reference#delete-users

**Comment by jperata** [comment]
This should include one additional step:
 If the user is deleted correctly an email to sales@bespoken.io should be sent (This can be a simple email with no template)
Subject: [Dashboard] User <User Email> has deleted his account
Content: The user with the email: <User Email>  has deleted his account

If there is an error during the user removal an email to dev@bespoken.io should be sent (This can be a simple email with no template):
Subject: [Dashboard] Errors during <User Email> account removal
Content: The user with the email: <User Email> has tried to remove it's account the errors are:
<Exception Stack>

**Comment by jperata** [comment]
The scenario where the user removal fails have been divided in two scenarios:
1) If source-api is unreacheable from dashboard, since source-api is in charge of the removal process, just show the user the error indicating to try again later.
2) If source-api works but there is an error during the process:
An email to dev@bespoken.io should be sent (This can be a simple email with no template):
Subject: [Dashboard] Errors during account removal
Content: The user with the email  `<User Email>` account removal
Content: The user with the email:` <User Email>` has tried to remove it's account the errors are:
`<Exception Stack> `

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-195
